clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:    
  frontend:
    image: node:8.11.4
    group: laravel
    commands:
      - node -v
      - npm -v
      - yarn --version
      - yarn config set registry 'https://registry.npm.taobao.org'
      - yarn install
      - yarn run production

  backend:    
    image: laradock/workspace:2.2-7.1
    group: laravel
    commands:
      - php -v
      - composer -v
      - composer config -g repo.packagist composer https://packagist.phpcomposer.com
      - cp .env.example .env
      - composer install --prefer-dist
      - php artisan key:generate
      - php artisan migrate
      - ./vendor/bin/phpunit
      - mkdir ../release
      - tar -czf ../release/release.tar.gz --exclude node_modules --exclude vendor --exclude .env --exclude *.lock .

  scp:
    image: appleboy/drone-scp
    host: 118.24.46.157
    username: root
    secrets: [ ssh_key ]
    target: /var/www/php_docker_env/www/html/laranaire
    source: ../release/release.tar.gz
    strip_components: 1
    rm: true
    when:
      event: tag
      status: [ success ]

  ssh:
    image: appleboy/drone-ssh
    host: 118.24.46.157
    username: root
    secrets: [ ssh_key ]
    script:    
      - cd /var/www/php_docker_env/www/html/laranaire
      - tar -xzf release.tar.gz
      - rm release.tar.gz
      - composer install --optimize-autoloader --no-dev
      - /var/www/deploy.sh
      - php artisan key:generate
      # - php artisan migrate
      - sudo chmod -R 777 storage bootstrap/cache
      # - php artisan config:cache
      # - php artisan route:cache
    when:
      event: tag
      status: [ success ]

services:
  redis:
    image: redis:latest

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
